# Generated by Django 3.1.4 on 2020-12-24 07:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='content[:5]', unique=True),
        ),
    ]
